---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: openjdk-8

inputs:
- name: hello-concourse-repo
outputs:
- name: build/libs
- name: src/main/docker

run:
  path: hello-concourse-repo/ci/build.sh

caches:
    - path: .gradle/
