---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: java
    tag: openjdk-8

inputs:
- name: hello-concourse-repo
outputs:
- name: out

run:
  path: hello-concourse/ci/build.sh

caches:
    - path: .gradle/
