---
resources:
- name: hello-concourse-repo
  type: git
  source:
    uri: https://github.com/ractive/hello-concourse.git
- name: hello-councourse-docker-image
  type: docker-image

jobs:
- name: gradle-build
  public: true
  plan:
  - get: hello-concourse-repo
    trigger: true
  - task: build
    file: hello-concourse-repo/ci/build.yml
  - task: ls
    file: hello-concourse-repo/ci/find.yml
