---
resources:
- name: hello-concourse
  type: git
  source:
    uri: https://github.com/ractive/hello-concourse.git

jobs:
- name: gradle-build
  public: true
  plan:
  - get: hello-concourse
    trigger: true
  - task: build
    file: hello-concourse/ci/build.yml
